name: CI Workflow
#when to execute these action is written inside on
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#What to execute is written inside jobs
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest streamlit

    - name: Run tests
      run: |
        pytest _test.py